// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://howmbtewstzrmnydqmuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvd21idGV3c3R6cm1ueWRxbXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTE0NDcsImV4cCI6MjA1OTYyNzQ0N30.56RmKe25I4f-EXOCLw_xnWW3VrxgC9dPQT_rGDvPY-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);